apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory2
  labels:
    app: inventory2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory2
  template:
    metadata:
      labels:
        app: inventory2
    spec:
      containers:
      - name: inventory2
        image: balavigneswaran/spring-cloud/inventory-pks:0.0.1-SNAPSHOT
        imagePullPolicy: Never
        resources:
          limits:
            memory: "0.5G"
            cpu: "0.25"
        ports:
        - containerPort: 8283
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: dev
        envFrom:
          - configMapRef:
              name: inventory2-env
---
apiVersion: v1
kind: Service
metadata:
  name: inventory2
  labels:
    app: inventory2
    primary-port-name: http
spec:
  type: LoadBalancer
  selector:
    app: inventory2
  ports:
  - port: 8283
    targetPort: 8283
    protocol: TCP
    name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory2-env
  labels:
    app: inventory2
data:
  PORT: "8283"
  KUBERNETES: "true"
  KUBE_RELOAD_MODE: polling
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-pks-dev
  labels:
    app: inventory2
data:
  application-dev.yaml: |-
      app:
        qty:
          limit: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-pks-default
  labels:
    app: inventory2
data:
  application.yaml: |-
    server:
      port: ${PORT:8183}
    app:
      qty:
        limit: 10
        adjustment: 2
        enabled: true
    spring:
      application:
        name: inventory
      datasource:
        url: "jdbc:h2:mem:testdb"
        driver-class-name: org.h2.Driver
        username: sa
        password: password
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    resilience4j:
      circuitbreaker:
        #    circuit-breaker-aspect-order: 1
        metrics:
          enabled: true
        configs:
          default:
            registerHealthIndicator: true
            slidingWindowSize: 120
            slidingWindowType: TIME_BASED
            failureRateThreshold: 49
            slowCallDurationThreshold: 30000
            slowCallRateThreshold: 74
            permittedNumberOfCallsInHalfOpenState: 2
            #      maxWaitDurationInHalfOpenState: 0
            minimumNumberOfCalls: 4
            waitDurationInOpenState: 30000
            automaticTransitionFromOpenToHalfOpenEnabled: false
        instances:
          slowService:
            baseConfig: default
            slidingWindowSize: 120
          fastService:
            baseConfig: default
            slidingWindowSize: 60
      retry:
        #    retry-aspect-order: 2
        metrics:
          enabled: true
        configs:
          default:
            maxAttempts: 3
            waitDuration: 500ms
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
        instances:
          slowService:
            #        baseConfig: default
            maxAttempts: 5
            waitDuration: 500ms
          fastService:
            maxAttempts: 3
            waitDuration: 500ms
        timelimiter:
          instances:
            backendA:
              timeoutDuration: 2s
              cancelRunningFuture: true
            backendB:
              timeoutDuration: 1s
              cancelRunningFuture: false
    management:
      endpoints:
        enabled-by-default: false
        web:
          exposure:
            include: health, info, circuitbreakers, metrics
      endpoint:
        info:
          enabled: true
        metrics:
          enabled: true
        health:
          enabled: true
          show-details: always
          probes:
            enabled: true
      health:
        readinessstate:
          enabled: true
        livenessstate:
          enabled: true
        defaults:
          enabled: true
        circuitbreakers:
          enabled: true
        kubernetes:
          enabled: true
