apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cron-job
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: pie
            image: alpine
            command: ["sh",  "-c", "echo 'Hello World CronJob!!!'"]
          restartPolicy: Never
