apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  ttlSecondsAfterFinished: 120
  activeDeadlineSeconds: 60
  completions: 4
  parallelism: 2
  template:
    spec:
      containers:
      - name: pie
        image: alpine
        command: ["sh",  "-c", "echo 'Hello World!!!'"]
      restartPolicy: Never
