apiVersion: v1
kind: Service
metadata:
  name: prod
  labels:
    app: prod
spec:
  type: LoadBalancer
  selector:
    app: green # blue
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
